version: '3.9'

services:
  web:
    build: .
    container_name: gloryphonic_web
    expose:
      - "8080"
    volumes:
      - static_volume:/app/static
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    container_name: gloryphonic_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    container_name: gloryphonic_certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/www/certbot
    entrypoint: "/bin/sh -c '
      certbot certonly --webroot --webroot-path=/var/www/certbot \
      --email gloryphonic@gmail.com \
      --agree-tos \
      --no-eff-email \
      -d gloryphonic-api.ddns.net
    '"

volumes:
  static_volume:
  certbot-etc:
  certbot-var:
