server {
    listen 80;
    server_name api.gloryphonic.net;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name api.gloryphonic.net;

    ssl_certificate /etc/letsencrypt/live/api.gloryphonic.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.gloryphonic.net/privkey.pem;

    client_max_body_size 100M;

    location /static/ {
        alias /app/staticfiles/;
    }

    location / {
        proxy_pass http://gloryphonic_web:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
