# Generated by Django 5.2 on 2025-11-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("band", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bandvideo",
            name="playlist",
            field=models.CharField(max_length=255),
        ),
    ]
