# Generated by Django 5.2 on 2025-06-10 21:13

import user.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                max_length=355,
                null=True,
                upload_to=user.utills.avatar_upload_path,
            ),
        ),
    ]
