# Generated by Django 5.2 on 2025-06-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_album_follower"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="facebook",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="instagram",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="spotify",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="youtube",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="youtube_music",
            field=models.URLField(blank=True, null=True),
        ),
    ]
