# Generated by Django 5.2 on 2025-07-01 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_user_facebook_user_instagram_user_spotify_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="facebook",
        ),
        migrations.RemoveField(
            model_name="user",
            name="instagram",
        ),
        migrations.RemoveField(
            model_name="user",
            name="spotify",
        ),
        migrations.RemoveField(
            model_name="user",
            name="youtube",
        ),
        migrations.RemoveField(
            model_name="user",
            name="youtube_music",
        ),
        migrations.CreateModel(
            name="SocialLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facebook", models.URLField(blank=True, null=True)),
                ("instagram", models.URLField(blank=True, null=True)),
                ("youtube", models.URLField(blank=True, null=True)),
                ("spotify", models.URLField(blank=True, null=True)),
                ("youtube_music", models.URLField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
