# Generated by Django 5.2 on 2025-07-01 13:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_remove_user_facebook_remove_user_instagram_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationapplication",
            name="country",
            field=models.CharField(default="Ukraine", max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="RegistrationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.registrationapplication",
                    ),
                ),
            ],
        ),
    ]
