# Generated by Django 5.2 on 2025-07-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="role",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
