# Generated by Django 5.2 on 2025-08-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_member_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[("User", "User"), ("Manager", "Manager"), ("Admin", "Admin")],
                default="User",
                max_length=10,
            ),
        ),
    ]
