# Generated by Django 5.2 on 2025-08-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_user_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name="user",
            old_name="status",
            new_name="role",
        ),
        migrations.AddField(
            model_name="user",
            name="genres",
            field=models.ManyToManyField(related_name="groups", to="user.genre"),
        ),
    ]
