# Generated by Django 5.2 on 2025-08-31 11:22

import user.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_genre_rename_status_user_role_user_genres"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=user.utils.cover_image_upload_path
            ),
        ),
    ]
