# Generated by Django 5.2 on 2025-11-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uservideo",
            name="video",
        ),
        migrations.AddField(
            model_name="uservideo",
            name="playlist",
            field=models.URLField(default="https://www.youtube.com/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="pseudonym",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="sociallinks",
            name="facebook",
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="sociallinks",
            name="instagram",
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="sociallinks",
            name="spotify",
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="sociallinks",
            name="youtube",
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="sociallinks",
            name="youtube_music",
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
