# Generated by Django 5.2 on 2025-11-11 15:39

import user.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_remove_uservideo_video_uservideo_playlist_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Band",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("country", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("slogan", models.TextField(blank=True, null=True)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=user.utils.cover_image_upload_path,
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(related_name="bands", to="user.genre"),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Member",
        ),
    ]
