# Generated by Django 5.2 on 2025-11-11 16:10

import django.db.models.deletion
import user.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0017_remove_user_cover_image_remove_user_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BandImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=user.utils.user_image_upload_path),
                ),
                (
                    "band",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="user.band",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="UserImage",
        ),
    ]
