# Generated by Django 5.2 on 2025-11-11 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0019_bandvideo_delete_uservideo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sociallinks",
            name="user",
        ),
        migrations.AddField(
            model_name="sociallinks",
            name="band",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_links",
                to="user.band",
            ),
            preserve_default=False,
        ),
    ]
