# Generated by Django 5.2 on 2025-11-11 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0020_remove_sociallinks_user_sociallinks_band"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="album",
            name="artist",
        ),
        migrations.AddField(
            model_name="album",
            name="band",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="albums",
                to="user.band",
            ),
            preserve_default=False,
        ),
    ]
