# Generated by Django 5.2 on 2025-11-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0021_remove_album_artist_album_band"),
    ]

    operations = [
        migrations.AlterField(
            model_name="follower",
            name="followed_artists",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to="user.band"
            ),
        ),
    ]
