# Generated by Django 5.2 on 2025-11-11 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0022_alter_follower_followed_artists"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="user.band",
            ),
        ),
    ]
