# Generated by Django 5.2 on 2025-11-12 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0023_alter_comment_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="band",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="user.band",
            ),
        ),
    ]
