# Generated by Django 5.2 on 2025-11-12 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0024_alter_user_band"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bandvideo",
            name="band",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="user.band",
            ),
        ),
    ]
