# Generated by Django 5.2 on 2025-11-12 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("band", "0001_initial"),
        ("user", "0025_alter_bandvideo_band"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="band",
            name="genres",
        ),
        migrations.RemoveField(
            model_name="bandvideo",
            name="band",
        ),
        migrations.AlterField(
            model_name="user",
            name="band",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="band.band",
            ),
        ),
        migrations.RemoveField(
            model_name="bandimage",
            name="band",
        ),
        migrations.RemoveField(
            model_name="sociallinks",
            name="band",
        ),
        migrations.RemoveField(
            model_name="follower",
            name="followed_artists",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="group",
        ),
        migrations.DeleteModel(
            name="Album",
        ),
        migrations.DeleteModel(
            name="Genre",
        ),
        migrations.DeleteModel(
            name="BandVideo",
        ),
        migrations.DeleteModel(
            name="BandImage",
        ),
        migrations.DeleteModel(
            name="SocialLinks",
        ),
        migrations.DeleteModel(
            name="Follower",
        ),
        migrations.DeleteModel(
            name="Band",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
